### ISSUE TITLE
Display image and onlclick event

### ISSUE THREAD

**Issue by gery** [UnGast/swift-cross-platform-gui-example#7]
Can you implement this?
I would use this framework for my strategy game.

**Comment by UnGast** [comment]
There is an experimental implementation of an ImageView which can display Images that are created with the "swim" library: [github.com/t-ae/swim](https://github.com/t-ae/swim).
Mouse events and especially click events are supported fairly well already. You can declare any Widget as conforming to GUIMouseEventConsumer and receive mouse events.

That being said, I do not recommend that you use my library right now. There is not much documentation and the whole thing is pretty slow. I'm currently focusing on designing a good API and will rewrite big chunks of the code. If you were to use it now, your code would break very soon, because of the changes I will make.

Feel free however, to make feature requests and pull requests.
